### ISSUE TITLE
lstm-VAEを用いたフォーム特徴量抽出

### ISSUE THREAD

**Issue by KohsukeIde** [KohsukeIde/project_research-A#3]
### WHY

- 経験者のフォームを学習させたモデルで初心者のフォームに推論をかけるとキーポイントが揺れている
- そもそも経験者のフォームの特徴をうまく学習できていない

### WHAT

- 学習で用いた経験者のフォームを入力としたときに、出力として入力とほとんど同じものを得る（could not be accomplished）
- 特徴量が学習できていたら、再度初心者のフォームに対して推論を行う。

### TO DO
- [x] モデルの評価: モデルの挙動を理解するために、中間層の出力を可視化する、潜在空間を解析するなど
- [x] データの前処理の見直し: 入力データの品質に問題があるかもしれません。データのクリーニングやノイズ除去、正規化の手法を見直してみると良いでしょう。
- [x] 損失関数: 現在の損失関数は、MSEとKLダイバージェンスの合計である。時系列データの特性をよりよく捉えるために、他の損失関数を試してみる。例えば、時系列データの一貫性や動的特性に焦点を当てた損失関数を導入する。
- [x] LSTMのTuning: LSTMが時系列データの動的な特性を捉えるのに十分な容量がない可能性がある。LSTMの層の数や隠れ層のサイズを調整してみる。
- [x] 時系列の長さ変更: まだ時系列の長さがLSTMにとって扱いにくいものである可能性がある。さらに異なるサンプリングレートを試してみるか、より短い時系列に分割してみる。
- [ ] ポストプロセッシングのスムージング: モデルの出力に対してスムージングを行うことで、結果をさらに滑らかにすることができるかも。

上記で解決しない場合、アーキテクチャから考え直す。
### Reference
#2 #4

**Comment by KohsukeIde** [comment]
## Progress (08/08/23)
入力と出力の比較を行う。各キーポイントについて入力と出力のMAEとSTDを算出したものを指標とする。
![Screen Shot 2023-08-08 at 16 46 44](https://github.com/KohsukeIde/project_research/assets/89821472/bc2acb9e-fb98-4fa7-8ee0-e4d58788e0ec)

lstm中間層の分析
手法

- 最大活性化分析: 各隠れユニットが最も活性化する入力例を見つける。この方法は、ユニットが反応する特定の特徴を理解するのに役立つ。

- 感受野の可視化: これは畳み込みニューラルネットワークでよく使用される手法だが、RNNにも適用可能。各隠れユニットが最も反応する入力空間の部分を特定。




## TODO
lstmの隠れユニットの可視化（lstmがどのように動いているかを理解できるかも）

- 相関分析: 隠れユニットの活動とラベルとの間に相関があるかどうかを調べることで、ユニットが特定のタスクにどれだけ関連しているかを理解。

- t-SNEなどの次元削減技術の使用: 高次元の隠れユニットの活動を2Dまたは3Dにマップして可視化。特定のクラスターまたはパターンが視覚的に識別できる場合がある。

オーバーフィッティング以上の問題がありそう。
VAEでdenoiseしてから、DTWでフレームの比較/マッピングを行う

**Comment by KohsukeIde** [comment]
## Progress (08/09/23)
lstmの隠れそうがノイズインプット（とパディング部分？）に過剰に反応を示しているのでノイズに対する学習データの前処理を行う。
![Screen Shot 2023-08-09 at 20 29 49](https://github.com/KohsukeIde/project_research/assets/89821472/d1bce354-ab0c-4539-b987-c9ba9fd34d89)

特定の基準ジョイント（例：胴体の中心）に対して他のジョイントを正規化する方法なども考慮
![Screen Shot 2023-08-09 at 23 05 36](https://github.com/KohsukeIde/project_research/assets/89821472/c0ff68c9-433f-4765-99a9-1223f908e616)
loss増えた

## TODO
正規化されたデータの可視化
時期続き前処理の引き続き

**Comment by KohsukeIde** [comment]
## Progress (08/12/23)
前のフレームを使って外れ値の補完を行った。少し精度が上がった（MSE）。キーポイント移動のトレンドはなんとなく掴めている気がする。
![Screen Shot 2023-08-12 at 2 40 48](https://github.com/KohsukeIde/project_research/assets/89821472/108d5d5c-2814-4419-a62f-344dfacf54af)



## TODO
lstm中間層の確認
モデルの複雑化

**Comment by KohsukeIde** [comment]
## Progress (08/17/23)
中間層の確認はOK（lstmの中間層全部確認するのは無理/各ユニットが反応しているところはあんま統一性はなさそう）
lossの変更色々追加した（詳しくはNotion）

まだ連続性を学習できていない…

## TODO
エンコーダ外でのLSTMの使用:
- このアプローチでは、LSTMはエンコーダとデコーダの間に配置され、エンコーダの出力を受け取り、デコーダに渡す前にそれを変換
この設計の主な目的は、潜在変数の時間的な連続性やパターンを捉えること。これにより、モデルは潜在変数の時間的な動的特性を学習しやすくなる。

LSTMとアテンションの組み合わせ？

**Comment by KohsukeIde** [comment]
## Progress (08/23/23)
エンコーダ外でのLSTMの使用:
結果は以下のようになった。
![Screen Shot 2023-08-23 at 21 29 57](https://github.com/KohsukeIde/project_research/assets/89821472/189f27a0-9a05-4fa8-a3e3-bfe540cee2e1)
エンコーダー内部にlstmを埋め込んだものよりも再構築ができていない。（lstm/VAEのパラメタなどを変更しても大きな違いなし）

## TODO
lstm-VAEの構造を最適化　
無理だった違う手法でアプローチ（New Issue）
